# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSUCCESSTEST():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sUCCESSTEST(self):
    self.driver.get("https://platformrc.wyscout.com/app/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.ID, "login_username").send_keys("potekarsima1998@gmail.com")
    self.driver.find_element(By.ID, "login_password").click()
    self.driver.find_element(By.ID, "login_password").click()
    self.driver.find_element(By.ID, "login_password").click()
    self.driver.find_element(By.ID, "login_password").click()
    self.driver.find_element(By.ID, "login_password").click()
    element = self.driver.find_element(By.ID, "login_password")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "login_password").send_keys("pw_IndiaTest!")
    self.driver.find_element(By.ID, "login_button").click()
  
