# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestINCORRECT():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_iNCORRECT(self):
    # Test name: INCORRECT
    # Step # | name | target | value
    # 1 | open | /app/ | 
    self.driver.get("https://platformrc.wyscout.com/app/")
    # 2 | setWindowSize | 1366x728 | 
    self.driver.set_window_size(1366, 728)
    # 3 | type | id=login_username | potekarsima1998@gmail.com
    self.driver.find_element(By.ID, "login_username").send_keys("potekarsima1998@gmail.com")
    # 4 | click | id=login_password | 
    self.driver.find_element(By.ID, "login_password").click()
    # 5 | type | id=login_password | pw_IndiaT!
    self.driver.find_element(By.ID, "login_password").send_keys("pw_IndiaT!")
    # 6 | click | id=login_button | 
    self.driver.find_element(By.ID, "login_button").click()
    # 7 | click | css=.size-normal > .ae-close-botton-1 | 
    self.driver.find_element(By.CSS_SELECTOR, ".size-normal > .ae-close-botton-1").click()
    # 8 | click | css=.new-login-content | 
    self.driver.find_element(By.CSS_SELECTOR, ".new-login-content").click()
  
